enhancement:
  - changed-files:
      - any-glob-to-any-file: [ "docs/**", "!docs/.vuepress/**" ]

config:
  - changed-files:
      - any-glob-to-any-file: docs/.vuepress/**

i18n:
  - changed-files:
      - any-glob-to-any-file: [ "docs/en/**", "docs/ja/**" ]

workflow:
  - changed-files:
      - any-glob-to-any-file: [ ".github/**", ".mergify.yml", ".markdownlint-cli2.mjs" ]

documentation:
  - changed-files:
      - any-glob-to-any-file: [ "LICENSE", "README.md" ]

dependencies:
  - changed-files:
      - any-glob-to-any-file: [ "CNAME", "package.json", "package-lock.json", "tsconfig.json", ".prettierignore", ".gitmodules" ]
