name: Deploy blog
on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "CONTRIBUTORS.md"
      - "README.md"

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

#      - name: Install Deps
#        run: npm install

      - name: Build Blog
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: npm run build:vite
      #        run: |-
      #          npm run docs:build
      #          > docs/.vuepress/dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: gh-pages
          folder: dist
#  deploy-server:
#    runs-on: ubuntu-latest
#    needs: deploy-gh-pages
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#        with:
#          ref: gh-pages
#          fetch-depth: 0
#
#      - name: Deploy to Server
#        uses: easingthemes/ssh-deploy@v3.4.5
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
##          ARGS: "-avzr --delete"
#          SOURCE: ""
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}
#          TARGET: ${{ secrets.TARGET }}
